name: Java CI

on:
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest
    name: CI

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify